services:
  mongodb:
    image: mongo:latest
    container_name: medium-clone-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: medium-clone
    networks:
      - medium-clone-network
    restart: unless-stopped

  mongo-express:
    image: mongo-express:latest
    container_name: medium-clone-mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: medium-clone-mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_MONGODB_AUTH_DATABASE: admin
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: pass
    depends_on:
      - mongodb
    networks:
      - medium-clone-network
    restart: unless-stopped

networks:
  medium-clone-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
